const ScreenNames = {
    HOME: 'RentersHome',
    SELECTTYPE: 'SelectType',
    SHAREDSCREENS: 'SharedScreens',
    TRIP: 'Trip',
    TRIPDETAILS: 'TripDetails',
    LOGIN: 'Login',
    TERMCONDITION: 'TermsConditions',
    PRIVACYPOLICY: 'PrivacyPolicy',
    SIGNUP: 'SignUp',
    SPLASH:'Splash',
    FORGOTPASSWORD: 'ForgotPassword',
    PROFILE: 'Profile',
    EDITPROFILEPICTURE: 'EditProfilePicture',
    OFFERS: 'Offers',
    OFFERDETAILS: 'OfferDetails',
    HOMEBASE: 'HomeBase',
    NOTIFICATION: 'Notification',
    TRANSACTION: 'Transaction',
    TRANSACTIONDETAILS: 'TransactionDetails',
    TOPDESTINATIONDETAILS: 'TopDestinationDetails',
    FULLFEATURELIST: 'FullFeatureList',
    SEARCH: 'Search',
    REVIEWS: 'Reviews',
    SENDOFFER: 'SendOffer',
    LEAVERATING: 'LeaveRating',
    CHOOSEUSERTYPE: 'ChooseUserType',
    MAKEOFFER: 'MakeOffer',
    OWNERPROFILE: 'OwnerProfile',
    BOOKING: 'Booking',
    LOCATION: 'Location',
    EMAILVERIFICATION: 'EmailVerification',
    RESETPASSWORD: 'ResetPassword',
    CUSTOMOFFERS: 'CustomOffers',
    PHONENUMBER: 'PhoneNumber',
    GETHELP: 'GetHelp',
    FAQ: 'FAQ',
    ACCOUNTSETTING: 'AccountSetting',
    USERLOCATION: 'UserLocation',
    LOCATIONPERMISSION: 'LocationPermission',
    SAVED: 'Saved',
    LINKOFFERDETAILS: 'LinkOfferDetails',
    FILTER: 'Filter',
  }as const; 

  export type ScreenNamesType = typeof ScreenNames[keyof typeof ScreenNames];
  
  
export default ScreenNames;